name: Docker Image CI PHP81_Xdebug

on:
  push:
    branches: [ "master" ]
    paths:
      - 'php81_xdebug/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'php81_xdebug/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        uses: actions/checkout@v3
        name: Checkout
      -
        name: ls -la
        run: ls -la
      -
        uses: docker/login-action@v2
        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME_DEVENV }}
          password: ${{ secrets.DOCKERHUB_TOKEN_DEVENV }}
      -
        uses: docker/setup-buildx-action@v2 
        name: Setup buildx
      -
        name: Build the php81_xdebug
        run: docker buildx build --platform linux/amd64,linux/arm64 -t hakanbysal/php8.1-fpm-xdebug:latest --push ./php81_xdebug/.
