name: Docker Image CI PHP72_Xdebug

on:
  push:
    branches: [ "master" ]
    paths:
      - 'php72_xdebug/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'php72_xdebug/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        uses: actions/checkout@v3
        name: Checkout

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - uses: docker/login-action@v2
        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        uses: docker/setup-buildx-action@v2
        name: Setup buildx
      -
        name: Build the php72_xdebug
        run: docker buildx build --platform linux/amd64,linux/arm64 --cache-from=type=registry,ref=onuragtas/php7.2-fpm-xdebug:latest -t onuragtas/php7.2-fpm-xdebug:latest --push --debug ./php72_xdebug/.
