name: Docker Image CI PHP74_Xdebug

on:
  push:
    paths:
      - 'php74_xdebug/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'php74_xdebug/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        uses: actions/checkout@v3
        name: Checkout
      -
        name: ls -la
        run: ls -la
      -
        uses: docker/login-action@v2
        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        uses: docker/setup-buildx-action@v2 
        name: Setup buildx
      -
        name: Build the php74_xdebug
        run: docker buildx build --platform linux/amd64,linux/arm64 -t onuragtas/php7.4-fpm-xdebug:latest --push ./php74_xdebug/.
