name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        uses: actions/checkout@v3
        name: Checkout
      -
        name: ls -la
        run: ls -la
      -
        uses: docker/login-action@v2
        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        uses: docker/setup-buildx-action@v2 
        name: Setup buildx
      -
        name: Build the php56
        run: docker buildx build --platform linux/amd64,linux/arm64 -t onuragtas/php5.6-fpm:latest --push ./php56/.
      -
        name: Build the php71
        run: docker buildx build --platform linux/amd64,linux/arm64 -t onuragtas/php7.1-fpm:latest --push ./php71/.
      -
        name: Build the php72
        run: docker buildx build --platform linux/amd64,linux/arm64 -t onuragtas/php7.2-fpm:latest --push ./php72/.
      -
        name: Build the php74
        run: docker buildx build --platform linux/amd64,linux/arm64 -t onuragtas/php7.4-fpm:latest --push ./php74/.
      -
        name: Build the php56_xdebug
        run: docker buildx build --platform linux/amd64,linux/arm64 -t onuragtas/php5.6-fpm-xdebug:latest --push ./php56_xdebug/.
      -
        name: Build the php71_xdebug
        run: docker buildx build --platform linux/amd64,linux/arm64 -t onuragtas/php7.1-fpm-xdebug:latest --push ./php71_xdebug/.
      -
        name: Build the php72_xdebug
        run: docker buildx build --platform linux/amd64,linux/arm64 -t onuragtas/php7.2-fpm-xdebug:latest --push ./php72_xdebug/.
      -
        name: Build the php74_xdebug
        run: docker buildx build --platform linux/amd64,linux/arm64 -t onuragtas/php7.4-fpm-xdebug:latest --push ./php74_xdebug/.
